import { mkdir, readFile, rename, unlink, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { assess, createProfile, families, generateTask, publicTask, type Answer, type ExamType, type FamilyId, type Profile, type Task } from '../domain';
import { acknowledgeRender, applyCommand, createScene, reportRenderFailure, setAiEnabled, undoAgentAction, updateStudent, type SceneOperation, type SceneState } from '../scene';
import type { AckRequest, AttemptAction, AttemptSummary, AttemptView, Catalog, CreateAttempt, HelpLevel, HelpRequest, ToolState } from '../api-types';
import { allParts } from '../api-types';
import { runCodex } from '../../ai/runtime';

type Internal = { view: AttemptView; tasks: Record<string, Task>; seed: number; pendingText: Record<string, string>; examType: ExamType; assisted: boolean };
export interface Fp9Provider { reply(input: Fp9Prompt, signal: AbortSignal): Promise<{ text: string; operations: SceneOperation[]; inputTokens: number; outputTokens: number; elapsedMs: number }>; }
export type Fp9Prompt = { level: HelpLevel; question: string; task: ReturnType<typeof publicTask>; scene: unknown; recentActions: unknown[] };
const MAX_BODY = 48 * 1024, MAX_TEXT = 4000, MAX_CALLS = Number(process.env.FP9_AI_MAX_CALLS ?? 12), TIMEOUT = Number(process.env.FP9_AI_TIMEOUT_MS ?? 90_000);
const id = (x: unknown): x is string => typeof x === 'string' && /^[A-Za-z0-9._:-]{1,120}$/.test(x);
const str = (x: unknown, max = MAX_TEXT): x is string => typeof x === 'string' && x.length <= max;
const finite = (x: unknown): x is number => typeof x === 'number' && Number.isFinite(x);
const plain = (x: unknown): x is Record<string, unknown> => !!x && typeof x === 'object' && !Array.isArray(x);
const now = () => new Date().toISOString();
const blankTools = (): ToolState => ({ tab: 'calculator', expression: '', result: '', cells: {}, rows: 6 });
const clone = <T>(x: T): T => structuredClone(x);

export class LocalAttemptStore {
  constructor(readonly path = process.env.FP9_STORE_PATH ?? join(import.meta.dir, '../../../.local/fp9')) {}
  private file(id: string) { if (!id.startsWith('fp9-')) throw Error('Ugyldigt forsøgs-id.'); return join(this.path, `${id}.json`); }
  async save(value: Internal) { await mkdir(this.path, { recursive: true }); const file = this.file(value.view.id), tmp = `${file}.${crypto.randomUUID()}.tmp`; await writeFile(tmp, JSON.stringify(value)); await rename(tmp, file); }
  async get(id: string): Promise<Internal> { try { return JSON.parse(await readFile(this.file(id), 'utf8')) as Internal; } catch { throw Error('Forsøget findes ikke.'); } }
  async list(): Promise<AttemptSummary[]> { try { const files = await Array.fromAsync(new Bun.Glob('*.json').scan({ cwd: this.path, absolute: true })); const values = await Promise.all(files.map(async f => JSON.parse(await readFile(f, 'utf8')) as Internal)); return values.map(x => ({ id: x.view.id, createdAt: x.view.createdAt, status: x.view.status, examType: x.examType, assisted: x.assisted })); } catch { return []; } }
  async delete(id: string) { try { await unlink(this.file(id)); } catch { throw Error('Forsøget findes ikke.'); } }
}

export class CodexFp9Provider implements Fp9Provider {
  async reply(input: Fp9Prompt, signal: AbortSignal) {
    const schema = { type: 'object', additionalProperties: false, required: ['text','operations'], properties: { text: { type: 'string', maxLength: 1200 }, operations: { type: 'array', maxItems: 12, items: { type: 'object' } } } };
    const restriction = input.level === 'solution' ? 'Du må forklare en løsning og bruge givne kriterier.' : 'Giv ikke facit, regneeksempler med de konkrete tal eller komplette løsningstrin; hjælp eleven videre.';
    const result = await runCodex({ schema, signal, timeoutMs: TIMEOUT, prompt: `Du er dansk FP9-matematikguide. ${restriction} Du må kun foreslå dataoperationer i den viste scene, aldrig kode eller ændringer til elevens objekter. Returnér JSON efter schema.\n${JSON.stringify(input)}` });
    const out = result.output as Record<string, unknown>;
    if (!plain(out) || !str(out.text, 1200) || !Array.isArray(out.operations)) throw Error('Codex-svaret havde forkert form.');
    return { text: out.text, operations: out.operations as SceneOperation[], inputTokens: result.inputTokens, outputTokens: result.outputTokens, elapsedMs: result.elapsedMs };
  }
}

export class Fp9Service {
  private locks = new Map<string, Promise<void>>(); private aborts = new Map<string, AbortController>();
  constructor(readonly store = new LocalAttemptStore(), readonly provider: Fp9Provider | null = process.env.AI_PROVIDER === 'off' ? null : new CodexFp9Provider()) {}
  private async locked<T>(id: string, fn: () => Promise<T>): Promise<T> { const prior = this.locks.get(id) ?? Promise.resolve(); let release!: () => void; const next = new Promise<void>(r => release = r); this.locks.set(id, prior.then(() => next)); await prior; try { return await fn(); } finally { release(); if (this.locks.get(id) === next) this.locks.delete(id); } }
  catalog(): Catalog { return { families, sourceVersion: 'fp9-foundation-2026-09-09', sourceDate: '2026-09-09' }; }
  list() { return this.store.list(); }
  async load(id: string) { return this.project(await this.store.get(id)); }
  private project(x: Internal): AttemptView { return clone(x.view); }
  private elapsed(v: AttemptView) { return v.clock.elapsedSeconds + (v.clock.lastResumedAt ? Math.max(0, Math.floor((Date.now() - Date.parse(v.clock.lastResumedAt)) / 1000)) : 0); }
  private expired(v: AttemptView) { return v.profile.timingMinutes !== null && this.elapsed(v) >= v.profile.timingMinutes * 60 + v.clock.extraSeconds; }
  private checkRevision(v: AttemptView, n: unknown) { if (!Number.isSafeInteger(n) || n !== v.revision) throw Object.assign(Error('Forsøget er ændret et andet sted. Hent det igen før du gemmer.'), { status: 409 }); }
  async create(input: CreateAttempt) {
    if (!plain(input) || !['with-aids','without-aids'].includes(input.examType) || typeof input.aiEnabled !== 'boolean' || !['short','full','topic'].includes(input.length) || !['immediate','after-submit'].includes(input.feedback) || (input.timingMinutes !== null && (!Number.isSafeInteger(input.timingMinutes) || input.timingMinutes <= 0 || input.timingMinutes > 600))) throw Error('Ugyldige indstillinger for forsøget.');
    if (input.familyId !== undefined && (!id(input.familyId) || !families.some(f => f.id === input.familyId && f.status === 'implemented'))) throw Error('Den valgte opgavefamilie er ikke klar.');
    const seed = input.seed === undefined ? Math.floor(Math.random() * 2_000_000_000) : input.seed;
    if (!Number.isSafeInteger(seed)) throw Error('Seed skal være et sikkert heltal.');
    const familyIds: FamilyId[] = input.length === 'topic' ? [input.familyId ?? 'F06'] : ['F06','F13','F16'];
    const parts = input.length === 'topic' ? familyIds.flatMap(f => [0,1,2].map(v => generateTask(f, seed, v, input.examType))) : familyIds.map((f, i) => generateTask(f, seed + i, input.length === 'short' ? 0 : i % 3, input.examType));
    const attemptId = `fp9-${crypto.randomUUID()}`; const createdAt = now(); const profile = createProfile(input.examType, input.aiEnabled, { timingMinutes: input.timingMinutes, feedback: input.feedback });
    const tasks = Object.fromEntries(parts.map(t => [t.id, t])); const scenes = Object.fromEntries(parts.map(t => [t.id, setAiEnabled(createScene(attemptId, t.id, t.scene), input.aiEnabled)]));
    const groups = input.length === 'topic' ? [{ id: `group-${familyIds[0]}`, title: families.find(f => f.id === familyIds[0])!.title, parts: parts.map(publicTask) }] : parts.map(t => ({ id: `group-${t.familyId}`, title: t.title, parts: [publicTask(t)] }));
    const view: AttemptView = { schemaVersion: '1', id: attemptId, revision: 0, createdAt, profile, status: 'active', submittedAt: null, groups, answers: {}, notes: {}, scenes, visited: [parts[0]!.id], flagged: [], activeTaskId: parts[0]!.id, assistance: [], chat: {}, clock: { elapsedSeconds: 0, lastResumedAt: createdAt, extraSeconds: 0, events: [{ kind: 'resume', at: createdAt }] }, assessments: {}, tools: {}, aiUsage: { calls: 0, inputTokens: 0, outputTokens: 0, lastLatencyMs: null } };
    const internal: Internal = { view, tasks, seed, pendingText: {}, examType: input.examType, assisted: false }; await this.store.save(internal); return this.project(internal);
  }
  private mutate(id0: string, expected: unknown, fn: (x: Internal) => void | Promise<void>) { return this.locked(id0, async () => { const x = await this.store.get(id0); this.checkRevision(x.view, expected); await fn(x); x.view.revision++; await this.store.save(x); return this.project(x); }); }
  async action(id0: string, action: AttemptAction) {
    if (!plain(action) || !Number.isSafeInteger(action.expectedRevision) || !str(action.type, 20)) throw Error('Ugyldig handling.');
    if (action.type === 'ai' || action.type === 'submit') this.aborts.get(id0)?.abort();
    return this.mutate(id0, action.expectedRevision, async x => {
      const v = x.view; const task = (t: unknown) => { if (!id(t) || !x.tasks[t]) throw Error('Ukendt opgave.'); return t; };
      const editable = () => { if (v.status === 'submitted') throw Error('Forsøget er afleveret og kan ikke ændres.'); if (this.expired(v)) throw Error('Tiden er udløbet. Registrér ekstra tid eller aflever forsøget.'); };
      switch (action.type) {
        case 'answer': { editable(); const t = task(action.taskId); if (!id(action.questionId) || !x.tasks[t]!.questions.some(q => q.id === action.questionId) || !plain(action.answer) || !str(action.answer.text) || (action.answer.explanation !== undefined && !str(action.answer.explanation)) || (action.answer.points !== undefined && (!Array.isArray(action.answer.points) || action.answer.points.length > 20 || !action.answer.points.every(p => Array.isArray(p) && p.length === 2 && p.every(finite))))) throw Error('Ugyldigt svar.'); v.answers[t] = { ...(v.answers[t] ?? {}), [action.questionId]: clone(action.answer) }; break; }
        case 'note': { editable(); const t = task(action.taskId); if (!str(action.text)) throw Error('Noten er for lang.'); v.notes[t] = action.text; break; }
        case 'navigate': { const t = task(action.taskId); v.activeTaskId = t; if (!v.visited.includes(t)) v.visited.push(t); break; }
        case 'flag': { const t = task(action.taskId); if (typeof action.flagged !== 'boolean') throw Error('Flag skal være sand eller falsk.'); v.flagged = action.flagged ? [...new Set([...v.flagged,t])] : v.flagged.filter(i => i !== t); break; }
        case 'student': { editable(); const t = task(action.taskId); if (!Array.isArray(action.objects) || !Array.isArray(action.selection)) throw Error('Ugyldig konstruktion.'); v.scenes[t] = updateStudent(v.scenes[t]!, { objects: action.objects, selection: action.selection }); break; }
        case 'tools': { editable(); const t = task(action.taskId); if (!plain(action.value) || !['calculator','sheet','cas'].includes(action.value.tab as string) || !str(action.value.expression, 2000) || !str(action.value.result, 2000) || !plain(action.value.cells) || !Number.isSafeInteger(action.value.rows) || action.value.rows < 1 || action.value.rows > 200) throw Error('Ugyldig værktøjstilstand.'); v.tools[t] = clone(action.value); break; }
        case 'pause': { if (!v.clock.lastResumedAt) throw Error('Uret er allerede sat på pause.'); v.clock.elapsedSeconds = this.elapsed(v); v.clock.lastResumedAt = null; v.clock.events.push({ kind: 'pause', at: now() }); break; }
        case 'resume': { if (v.status === 'submitted') throw Error('Et afleveret forsøg kan ikke genoptages.'); if (this.expired(v)) throw Error('Tiden er udløbet. Registrér ekstra tid først.'); if (v.clock.lastResumedAt) throw Error('Uret kører allerede.'); v.clock.lastResumedAt = now(); v.clock.events.push({ kind: 'resume', at: v.clock.lastResumedAt }); break; }
        case 'extra': { if (!Number.isSafeInteger(action.seconds) || action.seconds < 1 || action.seconds > 8 * 3600) throw Error('Ekstra tid skal være mellem 1 sekund og 8 timer.'); v.clock.extraSeconds += action.seconds; v.clock.events.push({ kind: 'extra', at: now(), seconds: action.seconds }); break; }
        case 'ai': { if (typeof action.enabled !== 'boolean') throw Error('AI-status skal være sand eller falsk.'); v.profile.aiEnabled = action.enabled; for (const t of Object.keys(v.scenes)) v.scenes[t] = setAiEnabled(v.scenes[t]!, action.enabled); if (!action.enabled) x.pendingText = {}; break; }
        case 'feedback': { const t = task(action.taskId); if (!id(action.questionId) || !v.answers[t]?.[action.questionId]) throw Error('Gem et svar før du beder om feedback.'); if (v.profile.feedback === 'after-submit' && v.status !== 'submitted') throw Error('Feedback vises først efter aflevering i denne profil.'); const assessment = assess(x.tasks[t]!, action.questionId, v.answers[t]![action.questionId]!); v.assessments[t] = { ...(v.assessments[t] ?? {}), [action.questionId]: assessment }; v.assistance.push({ id: `feedback-${crypto.randomUUID()}`, taskId: t, level: 'question', source: 'feedback', at: now() }); break; }
        case 'undo': { editable(); const t = task(action.taskId); const latest = v.scenes[t]!.actionLedger.at(-1); if (!latest) throw Error('Der er ingen AI-forklaring at fortryde.'); const result = undoAgentAction(v.scenes[t]!, latest.actionId); if (result.status !== 'applied') throw Error(result.reason); v.scenes[t] = result.state; break; }
        case 'submit': { if (v.status === 'submitted') throw Error('Forsøget er allerede afleveret.'); v.clock.elapsedSeconds = this.elapsed(v); v.clock.lastResumedAt = null; v.status = 'submitted'; v.submittedAt = now(); for (const t of Object.keys(x.tasks)) for (const q of x.tasks[t]!.questions) if (v.answers[t]?.[q.id]) v.assessments[t] = { ...(v.assessments[t] ?? {}), [q.id]: assess(x.tasks[t]!, q.id, v.answers[t]![q.id]!) }; break; }
        default: throw Error('Ukendt handling.');
      }
    });
  }
  async help(id0: string, request: HelpRequest) {
    if (!plain(request) || !Number.isSafeInteger(request.expectedRevision) || !id(request.taskId) || !['question','hint','step','solution'].includes(request.level) || !str(request.question)) throw Error('Ugyldig hjælpesanmodning.');
    const start = await this.locked(id0, async () => { const x = await this.store.get(id0); this.checkRevision(x.view, request.expectedRevision); if (x.view.status === 'submitted') throw Error('Brug review efter aflevering.'); if (!x.view.profile.aiEnabled || !this.provider) throw Error('AI er slået fra på serveren eller i forsøget.'); if (x.view.aiUsage.calls >= MAX_CALLS) throw Error('AI-budgettet for dette forsøg er brugt.'); const t = x.tasks[request.taskId]; if (!t) throw Error('Ukendt opgave.'); const controller = new AbortController(); this.aborts.get(id0)?.abort(); this.aborts.set(id0, controller); return { x, t, controller, revision: x.view.revision, scene: x.view.scenes[request.taskId]! }; });
    const provider = this.provider!; let response; try { response = await provider.reply({ level: request.level, question: request.question, task: publicTask(start.t), scene: start.scene, recentActions: [...start.scene.recentActions].slice(-10) }, AbortSignal.any([start.controller.signal, AbortSignal.timeout(TIMEOUT + 5_000)])); } catch (e) { if (start.controller.signal.aborted) throw Object.assign(Error('AI-svaret blev annulleret, fordi forsøget ændrede sig.'), { status: 409 }); throw e; }
    return this.locked(id0, async () => { const x = await this.store.get(id0); if (this.aborts.get(id0) === start.controller) this.aborts.delete(id0); if (start.controller.signal.aborted || x.view.revision !== start.revision || !x.view.profile.aiEnabled || x.view.status !== 'active') throw Object.assign(Error('AI-svaret er forældet og blev ikke anvendt.'), { status: 409 }); x.view.aiUsage.calls++; x.view.aiUsage.inputTokens += response.inputTokens; x.view.aiUsage.outputTokens += response.outputTokens; x.view.aiUsage.lastLatencyMs = response.elapsedMs; x.assisted = true; x.view.assistance.push({ id: `help-${crypto.randomUUID()}`, taskId: request.taskId, level: request.level, source: 'ai', at: now() }); const scene = x.view.scenes[request.taskId]!;
      if (response.operations.length) { const command = { attemptId: x.view.id, sceneId: request.taskId, expectedRevision: scene.revision, policyRevision: scene.policyRevision, actionId: `ai-${crypto.randomUUID()}`, operations: response.operations }; const applied = applyCommand(scene, command); if (applied.status !== 'applied') throw Error(`AI-handlingen blev afvist: ${applied.reason}`); x.view.scenes[request.taskId] = applied.state; x.pendingText[request.taskId] = response.text; } else { x.view.chat[request.taskId] = [...(x.view.chat[request.taskId] ?? []), { role: 'student', text: request.question }, { role: 'guide', text: response.text }]; }
      x.view.revision++; await this.store.save(x); return this.project(x); });
  }
  async ack(id0: string, request: AckRequest) { if (!plain(request) || !id(request.taskId) || !str(request.token, 300) || !Number.isSafeInteger(request.revision) || typeof request.success !== 'boolean') throw Error('Ugyldig render-bekræftelse.'); return this.locked(id0, async () => { const x = await this.store.get(id0); const scene = x.view.scenes[request.taskId]; if (!scene) throw Error('Ukendt opgave.'); const result = request.success ? acknowledgeRender(scene, request) : reportRenderFailure(scene, request); if (result.status === 'rejected') throw Object.assign(Error(result.reason), { status: 409 }); x.view.scenes[request.taskId] = result.state; if (request.success && x.pendingText[request.taskId]) { x.view.chat[request.taskId] = [...(x.view.chat[request.taskId] ?? []), { role: 'guide', text: x.pendingText[request.taskId]! }]; } delete x.pendingText[request.taskId]; x.view.revision++; await this.store.save(x); return this.project(x); }); }
  async remove(id0: string) { this.aborts.get(id0)?.abort(); await this.store.delete(id0); }
  async export(id0: string) { const x = await this.store.get(id0); return { version: '1', exportedAt: now(), attempt: this.project(x), seed: x.seed, examType: x.examType }; }
  async import(value: unknown) { if (!plain(value) || value.version !== '1' || !plain(value.attempt) || !Number.isSafeInteger(value.seed) || (value.examType !== 'with-aids' && value.examType !== 'without-aids')) throw Error('Ugyldig eller ikke-understøttet eksport.'); const incoming = value.attempt as unknown as AttemptView; const exportExamType = value.examType as ExamType; const exportSeed = value.seed as number; if (incoming.schemaVersion !== '1' || !Array.isArray(incoming.groups) || !plain(incoming.profile) || incoming.profile.examType !== exportExamType) throw Error('Eksporten har en ugyldig forsøgsform.'); const candidateFamily = incoming.groups.length === 1 ? incoming.groups[0]!.parts[0]?.familyId : undefined; const fresh = await this.create({ examType: exportExamType, aiEnabled: false, length: incoming.groups.length === 1 && incoming.groups[0]!.parts.length === 3 ? 'topic' : 'short', familyId: candidateFamily as FamilyId | undefined, seed: exportSeed, timingMinutes: incoming.profile.timingMinutes, feedback: incoming.profile.feedback }); const x = await this.store.get(fresh.id); const expected = allParts(x.view).map(t => JSON.stringify(t)).sort().join('|'), actual = allParts(incoming).map(t => JSON.stringify(t)).sort().join('|'); if (expected !== actual) { await this.store.delete(x.view.id); throw Error('Eksportens opgavegrundlag passer ikke til den reproducerede variant.'); }
    // Only copy bounded public/student data after regenerated givens have matched.
    x.view.answers = clone(incoming.answers ?? {}); x.view.notes = clone(incoming.notes ?? {}); x.view.visited = Array.isArray(incoming.visited) ? incoming.visited.filter(i => id(i) && x.tasks[i]) : x.view.visited; x.view.flagged = Array.isArray(incoming.flagged) ? incoming.flagged.filter(i => id(i) && x.tasks[i]) : []; x.view.activeTaskId = x.tasks[incoming.activeTaskId] ? incoming.activeTaskId : x.view.activeTaskId; x.view.assistance = Array.isArray(incoming.assistance) ? incoming.assistance.filter(a => plain(a) && id(a.id) && id(a.taskId) && ['question','hint','step','solution'].includes(a.level as string) && ['ai','local','feedback'].includes(a.source as string) && str(a.at)).map(a => a as AttemptView['assistance'][number]) : []; x.view.status = incoming.status === 'submitted' ? 'submitted' : 'active'; x.view.submittedAt = x.view.status === 'submitted' && str(incoming.submittedAt) ? incoming.submittedAt : null; x.view.profile.aiEnabled = false; for (const t of Object.keys(x.view.scenes)) x.view.scenes[t] = setAiEnabled(x.view.scenes[t]!, false); if (x.view.status === 'submitted') for (const t of Object.keys(x.tasks)) for (const q of x.tasks[t]!.questions) if (x.view.answers[t]?.[q.id]) x.view.assessments[t] = { ...(x.view.assessments[t] ?? {}), [q.id]: assess(x.tasks[t]!, q.id, x.view.answers[t]![q.id]!) }; x.view.revision = 0; await this.store.save(x); return this.project(x); }
}

export function createFp9Api(service = new Fp9Service()) { return async (request: Request): Promise<Response> => { const url = new URL(request.url); const fail = (e: unknown) => Response.json({ error: e instanceof Error ? e.message : 'Uventet serverfejl.' }, { status: (e as { status?: number })?.status ?? 400 }); if (!['127.0.0.1','localhost'].includes(url.hostname) || (request.headers.get('origin') && request.headers.get('origin') !== url.origin)) return Response.json({ error: 'Kun lokal adgang.' }, { status: 403 }); const parts = url.pathname.split('/').filter(Boolean); try { if (url.pathname === '/api/fp9/catalog' && request.method === 'GET') return Response.json(service.catalog()); if (url.pathname === '/api/fp9/attempts' && request.method === 'GET') return Response.json({ attempts: await service.list() }); if (url.pathname === '/api/fp9/attempts' && request.method === 'POST') return Response.json(await service.create(await json(request) as unknown as CreateAttempt), { status: 201 }); if (url.pathname === '/api/fp9/import' && request.method === 'POST') return Response.json(await service.import((await json(request)).export), { status: 201 }); const attempt = parts[3]; if (!id(attempt)) return Response.json({ error: 'Ikke fundet.' }, { status: 404 }); if (parts.length === 4 && request.method === 'GET') return Response.json(await service.load(attempt)); if (parts.length === 4 && request.method === 'DELETE') { await service.remove(attempt); return new Response(null, { status: 204 }); } if (parts[4] === 'action' && request.method === 'POST') return Response.json(await service.action(attempt, await json(request) as unknown as AttemptAction)); if (parts[4] === 'help' && request.method === 'POST') return Response.json(await service.help(attempt, await json(request) as unknown as HelpRequest)); if (parts[4] === 'ack' && request.method === 'POST') return Response.json(await service.ack(attempt, await json(request) as unknown as AckRequest)); if (parts[4] === 'export' && request.method === 'GET') return Response.json(await service.export(attempt)); return Response.json({ error: 'Ikke fundet.' }, { status: 404 }); } catch (e) { return fail(e); } }; }
async function json(request: Request): Promise<Record<string, unknown>> { if (!request.headers.get('content-type')?.startsWith('application/json')) throw Object.assign(Error('Brug JSON.'), { status: 415 }); const text = await request.text(); if (text.length > MAX_BODY) throw Object.assign(Error('JSON-kroppen er for stor.'), { status: 413 }); try { const value = JSON.parse(text); if (!plain(value)) throw Error(); return value; } catch { throw Error('Ugyldig JSON.'); } }
