import { useEffect, useMemo, useState } from 'react';

type Family = 'analytisk' | 'trekant' | 'ugrupperet' | 'grupperet';
type Task = { id:string; title:string; story:string; variant:number; givens:string[]; question:string; unit:string; answerLabel:string; answer:number; tolerance:number; explanation:string; scene: { kind:'geo'|'data'; values:number[]; labels?:string[] } };
const families: { id:Family; tab:'PLANGEOMETRI'|'DESKRIPTIV STATISTIK'; title:string; subtitle:string }[] = [
  {id:'analytisk',tab:'PLANGEOMETRI',title:'Linjer og cirkler',subtitle:'Koordinater, hældning og afstand'},
  {id:'trekant',tab:'PLANGEOMETRI',title:'Trekanter i planen',subtitle:'Pythagoras, areal og trigonometriske regler'},
  {id:'ugrupperet',tab:'DESKRIPTIV STATISTIK',title:'Ugrupperede data',subtitle:'Gennemsnit, median og kvartiler'},
  {id:'grupperet',tab:'DESKRIPTIV STATISTIK',title:'Grupperede data',subtitle:'Frekvens, estimation og medianinterval'},
];
const rng=(n:number)=>{let x=(n>>>0)||1; return ()=>((x=(x*1664525+1013904223)>>>0)/4294967296)};
const r=(f:()=>number,a:number,b:number)=>a+Math.floor(f()*(b-a+1));
const fmt=(n:number)=>Number.isInteger(n)?String(n):n.toFixed(2).replace('.',',');
export function makeTask(family:Family, seed:number, variant:number):Task {
  const random=rng(seed + variant*1009); const id=`${family}:${seed}:${variant%3}`; const v=variant%3;
  if(family==='analytisk') {
    if(v===0){const x1=r(random,-4,0), y1=r(random,-3,3), dx=r(random,2,5), m=r(random,-3,3)||2, x2=x1+dx,y2=y1+m*dx; return {id,title:'Linje gennem to punkter',story:'En cykelrute tegnes i et koordinatsystem.',variant:v,givens:[`A(${x1}; ${y1})`,`B(${x2}; ${y2})`],question:'Bestem linjens hældningskoefficient a.',unit:'',answerLabel:'a =',answer:m,tolerance:.001,explanation:'Brug a = (y₂ − y₁)/(x₂ − x₁).',scene:{kind:'geo',values:[x1,y1,x2,y2]}};}
    if(v===1){const m=r(random,1,4), x=r(random,-2,3), y=r(random,-3,4); return {id,title:'Vinkelret linje',story:'En rampe skal stå vinkelret på en markeret sti.',variant:v,givens:[`Stiens hældning er ${m}`,`Rampen går gennem P(${x}; ${y})`],question:'Angiv rampens hældning.',unit:'',answerLabel:'hældning =',answer:-1/m,tolerance:.01,explanation:'Vinkelrette linjer har hældninger, der ganges til −1.',scene:{kind:'geo',values:[x,y,m,0]}};}
    const cx=r(random,-2,2),cy=r(random,-2,2),rad=r(random,2,5); return {id,title:'Cirklens radius',story:'En rund legeplads er målt op fra centrum.',variant:v,givens:[`Centrum C(${cx}; ${cy})`,`Punkt på cirklen: P(${cx+rad}; ${cy})`],question:'Bestem radius.',unit:'enheder',answerLabel:'r =',answer:rad,tolerance:.001,explanation:'Radius er afstanden fra centrum til et punkt på cirklen.',scene:{kind:'geo',values:[cx,cy,cx+rad,cy]}};
  }
  if(family==='trekant') {
    if(v===0){const a=r(random,3,8),b=r(random,4,9),c=Math.hypot(a,b);return {id,title:'Pythagoras',story:'En stige danner en retvinklet trekant med en væg.',variant:v,givens:[`Kateter: ${a} m og ${b} m`],question:'Hvor lang er hypotenusen? Afrund til 2 decimaler.',unit:'m',answerLabel:'c =',answer:c,tolerance:.011,explanation:'c² = a² + b², så c = √(a² + b²).',scene:{kind:'geo',values:[a,b,c]}};}
    if(v===1){const b=r(random,4,10),h=r(random,3,8);return {id,title:'Trekantens areal',story:'Et trekantet blomsterbed skal dækkes med jord.',variant:v,givens:[`Grundlinje: ${b} m`,`Højde: ${h} m`],question:'Bestem trekantens areal.',unit:'m²',answerLabel:'A =',answer:b*h/2,tolerance:.001,explanation:'A = ½ · grundlinje · højde.',scene:{kind:'geo',values:[b,h,b*h/2]}};}
    const a=r(random,5,10), b=r(random,5,10), C=r(random,35,75), c=Math.sqrt(a*a+b*b-2*a*b*Math.cos(C*Math.PI/180));return {id,title:'Cosinusrelationen',story:'To vandrestier mødes ved et udsigtspunkt.',variant:v,givens:[`a = ${a} km`,`b = ${b} km`,`C = ${C}°`],question:'Bestem siden c. Afrund til 2 decimaler.',unit:'km',answerLabel:'c =',answer:c,tolerance:.011,explanation:'c² = a² + b² − 2ab cos(C).',scene:{kind:'geo',values:[a,b,C]}};
  }
  if(family==='ugrupperet') { const vals=Array.from({length:7},()=>r(random,2,12)).sort((a,b)=>a-b);
    if(v===0){const mean=vals.reduce((a,b)=>a+b,0)/vals.length;return {id,title:'Gennemsnit og median',story:'Syv elever tæller dagens cykelture.',variant:v,givens:[`Data: ${vals.join(', ')}`],question:'Bestem gennemsnittet. Afrund til 2 decimaler.',unit:'ture',answerLabel:'gennemsnit =',answer:mean,tolerance:.011,explanation:'Læg alle observationer sammen og divider med antallet.',scene:{kind:'data',values:vals}};}
    if(v===1){const q1=(vals[1]!+vals[2]!)/2;return {id,title:'Kvartiler og boksplot',story:'Et hold sammenligner tider på en kort bane.',variant:v,givens:[`Sorterede tider: ${vals.join(', ')}`, 'Konvention: medianen af hver halvdel; central observation udelades.'],question:'Bestem nedre kvartil Q1.',unit:'min',answerLabel:'Q1 =',answer:q1,tolerance:.001,explanation:'Del data ved medianen og find medianen i den nedre halvdel.',scene:{kind:'data',values:vals}};}
    const base=vals.slice(0,6), out=base[5]!+20,mean=[...base,out].reduce((a,b)=>a+b,0)/7;return {id,title:'Effekt af en outlier',story:'En fejlregistreret meget lang leveringstid undersøges.',variant:v,givens:[`Data: ${[...base,out].join(', ')}`,`Den største værdi (${out}) er en outlier.`],question:'Bestem gennemsnittet med outlieren. Afrund til 2 decimaler.',unit:'min',answerLabel:'gennemsnit =',answer:mean,tolerance:.011,explanation:'Gennemsnittet påvirkes kraftigt af en enkelt meget stor værdi; medianen er mere robust.',scene:{kind:'data',values:[...base,out]}};
  }
  const counts=[r(random,3,8),r(random,5,12),r(random,4,10),r(random,2,7)], mids=[5,15,25,35];
  if(v===0){const total=counts.reduce((a,b)=>a+b,0);return {id,title:'Frekvens og kumuleret frekvens',story:'Besøgende tælles i fire tydelige aldersintervaller.',variant:v,givens:counts.map((c,i)=>`${i*10}–${i*10+9} år: ${c}`),question:'Hvor mange observationer er der i alt?',unit:'personer',answerLabel:'n =',answer:total,tolerance:.001,explanation:'Læg alle hyppigheder sammen. Kumuleret frekvens bygges derefter op trin for trin.',scene:{kind:'data',values:counts,labels:['0–9','10–19','20–29','30–39']}};}
  if(v===1){const total=counts.reduce((a,b)=>a+b,0),estimate=counts.reduce((s,c,i)=>s+c*mids[i]!,0)/total;return {id,title:'Grupperet gennemsnit',story:'Pakker er vejet i intervaller på 10 kg.',variant:v,givens:counts.map((c,i)=>`${i*10}–${i*10+9} kg: ${c}`),question:'Bestem det vægtede gennemsnitsestimat med klassemidtpunkterne 5, 15, 25 og 35. Afrund til 2 decimaler.',unit:'kg',answerLabel:'estimat =',answer:estimate,tolerance:.011,explanation:'Dette er et estimat: gang hvert klassemidtpunkt med sin hyppighed og divider med n.',scene:{kind:'data',values:counts,labels:['0–9','10–19','20–29','30–39']}};}
  const total=counts.reduce((a,b)=>a+b,0), target=total/2; let acc=0, idx=0; while(acc+counts[idx]!<target){acc+=counts[idx]!;idx++;} return {id,title:'Medianinterval',story:'Ventetider er registreret i halve time-intervaller.',variant:v,givens:counts.map((c,i)=>`${i*10}–${i*10+9} min: ${c}`),question:'Hvilket interval indeholder medianen? Svar med intervallets nederste grænse.',unit:'min',answerLabel:'nedre grænse =',answer:idx*10,tolerance:.001,explanation:'Find den observation, der ligger midt i den kumulerede hyppighed. Intervallerne er tydeligt afgrænsede.',scene:{kind:'data',values:counts,labels:['0–9','10–19','20–29','30–39']}};
}

function Visual({task,explore,setExplore}:{task:Task;explore:number;setExplore:(n:number)=>void}) { if(task.scene.kind==='data') return <div className="ma-visual"><div className="ma-bars">{task.scene.values.map((v,i)=><div key={i} className="ma-bar-wrap"><div className="ma-bar" style={{height:`${Math.max(12,v*10)}px`}}/><span>{task.scene.labels?.[i] ?? v}</span></div>)}</div><p>Opgavens data er vist her. Søjlerne er kun en visning — aflæs ikke facit fra dem.</p></div>; const [a=0,b=0,c=0,d=0]=task.scene.values; return <div className="ma-visual"><svg viewBox="0 0 360 190" role="img" aria-label="Koordinatskitse"><path d="M25 160H340M55 180V15" stroke="#879486"/><path d={`M80 ${140-b*6} L${250+c*5} ${130-d*6}`} stroke="#31745b" strokeWidth="3"/><circle cx="80" cy={140-b*6} r="5" fill="#31745b"/><circle cx={250+c*5} cy={130-d*6} r="5" fill="#31745b"/><text x="60" y="25">skitse · ikke målfast</text></svg><label>Undersøgelsespunkts placering <input type="range" min="0" max="10" value={explore} onChange={e=>setExplore(Number(e.target.value))}/></label><p>Opgavens givne værdier ændres ikke. Din udforskning: {explore}.</p></div> }

export function MatematikAApp(){const [tab,setTab]=useState<'PLANGEOMETRI'|'DESKRIPTIV STATISTIK'>('PLANGEOMETRI');const [family,setFamily]=useState<Family>('analytisk');const [seed,setSeed]=useState(()=>Math.floor(Math.random()*1e8));const [variant,setVariant]=useState(0);const task=useMemo(()=>makeTask(family,seed,variant),[family,seed,variant]);const [answer,setAnswer]=useState('');const [result,setResult]=useState('');const [ai,setAi]=useState(false);const [help,setHelp]=useState('');const [note,setNote]=useState('');const [level,setLevel]=useState('passer');const [explore,setExplore]=useState(5);useEffect(()=>{setAnswer('');setResult('');setHelp('');setExplore(5)},[task.id]);useEffect(()=>localStorage.setItem('matematik-a-pilot',JSON.stringify({family,seed,variant,note,level})),[family,seed,variant,note,level]); const available=families.filter(x=>x.tab===tab);
 const check=()=>{const n=Number(answer.replace(',','.'));setResult(Number.isFinite(n)&&Math.abs(n-task.answer)<=task.tolerance?'Godt regnet — dit svar passer med opgavens kontrol.':'Ikke helt. Tjek enheder, afrunding og mellemregning.');};const exportFeedback=()=>{const blob=new Blob([JSON.stringify({task:task.id,sværhedsgrad:level,note,createdAt:new Date().toISOString()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='matematik-a-feedback.json';a.click();URL.revokeObjectURL(a.href)};
 return <div className="ma-app"><header className="ma-header"><a className="brand" href="/">matematikværkstedet</a><span>LOKAL PILOT · STX</span><a href="/fp9">FP9-træning</a></header><main className="ma-main"><aside className="ma-nav"><p>MATEMATIK A · STX</p><h2>Træn en idé ad gangen</h2><div className="ma-tabs">{(['PLANGEOMETRI','DESKRIPTIV STATISTIK'] as const).map(t=><button key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);setFamily(t==='PLANGEOMETRI'?'analytisk':'ugrupperet')}}>{t}</button>)}</div>{available.map(f=><button className="ma-family" aria-current={family===f.id?'page':undefined} onClick={()=>setFamily(f.id)} key={f.id}><strong>{f.title}</strong><small>{f.subtitle}</small></button>)}<p className="ma-limit">Første pilot med fire opgavegrupper. Ikke fuld Matematik A-dækning eller eksamenstræning.</p></aside><section className="ma-work"><p className="ma-kicker">{tab} · {task.title}</p><h1>{task.story}</h1><p>Variant {task.variant+1} af 3 · Seed {seed}</p><div className="ma-card"><div><h3>Givet</h3><ul>{task.givens.map(x=><li key={x}>{x}</li>)}</ul></div><Visual task={task} explore={explore} setExplore={setExplore}/></div><section className="ma-question"><h2>{task.question}</h2><label>{task.answerLabel}<input value={answer} onChange={e=>setAnswer(e.target.value)} inputMode="decimal" placeholder="Skriv dit svar"/> {task.unit}</label><button className="ma-primary" onClick={check}>Tjek svar</button><p role="status">{result}</p><div className="ma-actions"><button onClick={()=>setSeed(Math.floor(Math.random()*1e8))}>Ny opgave</button><button onClick={()=>setVariant(v=>(v+1)%3)}>Ny variant</button></div></section><section className="ma-feedback"><h3>Giv feedback</h3><select value={level} onChange={e=>setLevel(e.target.value)}><option value="let">Let</option><option value="passer">Passer</option><option value="svær">Svær</option><option value="forvirrende">Forvirrende</option></select><input value={note} onChange={e=>setNote(e.target.value)} maxLength={500} placeholder="Kort note (gemmes kun lokalt)"/><button onClick={exportFeedback}>Eksportér JSON</button></section></section><aside className="ma-guide"><h2>Matematikguide</h2><label className="ma-toggle"><input type="checkbox" checked={ai} onChange={e=>setAi(e.target.checked)}/> AI-støtte {ai?'til':'fra'}</label><p>{ai?'AI-støtte er valgt. I denne lokale pilot bruges sikre, faste hjælpeformer; ingen opgavefacit sendes.':'Ingen AI-kald. Din opgave og scene bliver på denne enhed.'}</p><button onClick={()=>setHelp('Hint: '+task.explanation)}>Giv et hint</button><button onClick={()=>setHelp('Skridt: Skriv først de givne størrelser op, vælg derefter en relevant regel.')}>Vis næste skridt</button><button onClick={()=>setHelp('Forklaring: '+task.explanation)}>Forklar metode</button>{help&&<p className="ma-help">{help}</p>}<small>Hjælp er synlig og ændrer aldrig opgavens givne værdier.</small></aside></main></div>}
