import {useEffect,useRef,useState} from 'react';
import {choices,fmt,lesson,prompt,visibleFocus,steps,titles,validateContext,type Context,type Stage,type Topic} from './model';
import type {Reply} from './server';
import {Scene} from './Scene';
import './learning.css';

type Message={role:'student'|'guide';text:string};
type Work={first:string;second:string;choice:number;explanation:string};
type State={context:Context;furthest:Stage;prediction:number;explored:boolean;ai:boolean;assisted:boolean;work:Record<string,Work>;passed:Record<string,boolean>;attempts:Record<string,number>;messages:Message[];feedback:string};
const emptyWork=():Work=>({first:'',second:'',choice:-1,explanation:''});
const fresh=(topic:Topic):State=>({context:{topic,seed:1+Math.floor(Math.random()*99999),stage:0,explore:0},furthest:0,prediction:-1,explored:false,ai:true,assisted:false,work:{},passed:{},attempts:{},messages:[],feedback:''});
const storage='math-a-learning-v1';
function restore():State|null{try{const s=JSON.parse(localStorage.getItem(storage)||'null');if(!s)return null;validateContext(s.context);if(!Number.isInteger(s.furthest)||s.furthest<0||s.furthest>5||!s.work||!s.passed||!s.attempts||!Array.isArray(s.messages)||typeof s.feedback!=='string')return null;for(const v of Object.values(s.work) as Work[])if(!v||typeof v.first!=='string'||typeof v.second!=='string'||typeof v.explanation!=='string'||v.explanation.length>1200)return null;return {...s,ai:s.ai===true,assisted:s.assisted===true,messages:s.messages.filter((m:Message)=>m&&['student','guide'].includes(m.role)&&typeof m.text==='string').slice(-8)};}catch{return null;}}
async function post<T>(path:string,body:unknown,signal?:AbortSignal):Promise<T>{const r=await fetch('/api/learning/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal});const data=await r.json();if(!r.ok)throw Error(data.error||'Forbindelsen fejlede.');return data;}
export function LearningApp(){
 const [state,setState]=useState<State|null>(restore),[home,setHome]=useState(true),[status,setStatus]=useState(''),[error,setError]=useState(''),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[available,setAvailable]=useState(false),[guideOpen,setGuideOpen]=useState(false),[focus,setFocus]=useState('none');
 const revision=useRef(0),pending=useRef<AbortController|null>(null),sceneRoot=useRef<HTMLDivElement>(null),heading=useRef<HTMLHeadingElement>(null);
 const cancel=()=>{revision.current++;pending.current?.abort();pending.current=null;setBusy(false);};
 useEffect(()=>{fetch('/api/learning/status').then(r=>r.json()).then(v=>setAvailable(v.available===true)).catch(()=>setAvailable(false));return()=>pending.current?.abort();},[]);
 useEffect(()=>{if(state)try{localStorage.setItem(storage,JSON.stringify(state));}catch{setError('Dit arbejde kunne ikke gemmes i browseren. Behold siden åben.');}},[state]);
 useEffect(()=>{if(!home){heading.current?.focus();heading.current?.scrollIntoView({block:'start'});}},[home,state?.context.stage]);
 const update=(fn:(s:State)=>State)=>{cancel();setError('');setStatus('');setFocus('none');setState(s=>s?fn(s):s);};
 const start=(topic:Topic)=>{cancel();setState(fresh(topic));setHome(false);setGuideOpen(false);setError('');setStatus('');};
 if(home||!state)return <div className="learn"><header className="learn-header"><a href="/">matematikværkstedet</a><a href="/matematik-a/opgaver">Øvebibliotek</a></header><main className="learn-home"><p className="learn-eyebrow">MATEMATIK A · STX</p><h1>Forstå det.<br/>Undersøg det. Prøv selv.</h1><p className="learn-intro">To korte forløb i det, du arbejder med lige nu. Du starter med en idé og slutter med en ny opgave på egen hånd.</p>{state&&<button className="learn-primary" onClick={()=>setHome(false)}>Fortsæt: {titles[state.context.topic]} · trin {Math.min(state.context.stage+1,5)}</button>}<div className="learn-topic-grid"><button onClick={()=>start('geometry')}><span className="learn-topic-icon">↗</span><small>PLANGEOMETRI</small><h2>Hvad bestemmer en linjes hældning?</h2><p>Flyt et punkt. Se ændringen. Forklar, hvorfor linjen bliver stejlere eller fladere.</p><b>Start forløbet →</b></button><button onClick={()=>start('statistics')}><span className="learn-topic-icon">•••　•</span><small>DESKRIPTIV STATISTIK</small><h2>Hvornår er gennemsnittet misvisende?</h2><p>En enkelt lang ventetid ændrer historien. Undersøg forskellen på gennemsnit og median.</p><b>Start forløbet →</b></button></div><p className="learn-note">Fem trin · AI-hjælp undervejs · sidste opgave uden hjælp. Start af et nyt forløb erstatter dit aktuelle lokale forløb. Det øvrige øvebibliotek bevares.</p></main></div>;
 const c=state.context,work=state.work[c.stage]??emptyWork(),d=lesson(c),isTransfer=c.stage===4;
 const write=(patch:Partial<Work>)=>update(s=>({...s,work:{...s.work,[c.stage]:{...(s.work[c.stage]??emptyWork()),...patch}},passed:{...s.passed,[c.stage]:false}}));
 const go=(stage:Stage)=>{update(s=>({...s,context:{...s.context,stage},furthest:Math.max(s.furthest,stage) as Stage,messages:[]}));setGuideOpen(false);};
 const canNext=c.stage===0?state.prediction>=0:c.stage===1?state.explored:!!state.passed[c.stage]&&(c.stage!==4||work.explanation.trim().length>=12);
 async function assess(){
  if(!state)return;if(c.stage===4&&work.explanation.trim().length<12){setStatus('Skriv også en kort begrundelse, før du afleverer.');return;}const rev=revision.current;setError('');
  try{const result=await post<{correct:boolean;text:string}>('check',{context:c,answer:work});if(revision.current!==rev)return;setStatus(result.text);setState(s=>s?{...s,passed:{...s.passed,[c.stage]:result.correct},attempts:{...s.attempts,[c.stage]:(s.attempts[c.stage]??0)+1}}:s);}catch(e){setError(String(e));}
 }
 async function ask(){
  if(!state||!state.ai||c.stage>=4||!available||pending.current)return;
  const controller=new AbortController(),rev=revision.current,q=question.trim()||'Hjælp mig med at tænke videre i dette trin uden at give facit.';pending.current=controller;setBusy(true);setError('');setQuestion('');
  const history=state.messages;setState(s=>s?{...s,messages:[...s.messages,{role:'student',text:q}].slice(-8) as Message[]}:s);
  try{const r=await post<Reply&{revision:number}>('help',{context:c,answer:{...work,prediction:state.prediction},question:q,history,revision:rev,aiEnabled:true},controller.signal);
   if(controller.signal.aborted||revision.current!==rev||r.revision!==rev)return;
   const allowed=visibleFocus(c);
   if(typeof r.text!=='string'||!allowed.includes(r.focus)||(r.explore!==null&&(!Number.isInteger(r.explore)||c.stage!==1||r.explore<(c.topic==='geometry'?-6:0)||r.explore>(c.topic==='geometry'?8:20))))throw Error('Guidens ændring blev afvist.');
   setFocus(r.focus);setState(s=>s?{...s,assisted:true,context:{...s.context,explore:r.explore??s.context.explore}}:s);
   await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));
   if(controller.signal.aborted||revision.current!==rev)return;
   // Text can refer to a focus only if that layer exists at this learning stage.
   const visible=r.focus==='none'||!!sceneRoot.current?.querySelector(`[data-focus="${r.focus}"]`);
   setState(s=>s?{...s,messages:[...s.messages,{role:'guide',text:r.text+(r.explore!==null&&r.explore!==c.explore?'\nFiguren viser nu guidens eksempel. Prøv selv at ændre den.':'')+(!visible?'\nFremhævningen er ikke tilgængelig i dette trin.':'')}].slice(-8) as Message[]}:s);
  }catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Guiden kunne ikke svare.');}finally{if(pending.current===controller){pending.current=null;setBusy(false);}}
 }
 const exportFeedback=()=>{const blob=new Blob([JSON.stringify({version:1,topic:c.topic,seed:c.seed,prediction:state.prediction,answers:state.work,attempts:state.attempts,assisted:state.assisted,feedback:state.feedback},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='matematik-a-forloeb-feedback.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <div className="learn"><header className="learn-header"><button onClick={()=>{cancel();setHome(true);}}>← Dine forløb</button><span>MATEMATIK A · STX</span><a href="/matematik-a/opgaver">Øvebibliotek</a></header><main className="learn-layout"><div className="learn-main"><nav className="learn-steps" aria-label="Trin i forløbet">{steps.map((name,i)=><button key={name} disabled={i>state.furthest} aria-current={c.stage===i?'step':undefined} onClick={()=>go(i as Stage)}><span>{i+1}</span>{name}</button>)}</nav><p className="learn-eyebrow">{c.topic==='geometry'?'PLANGEOMETRI':'DESKRIPTIV STATISTIK'} · {c.stage<5?`TRIN ${c.stage+1} AF 5`:'DIT TILBAGEBLIK'}</p><h1 ref={heading} tabIndex={-1}>{c.stage===5?'Hvad tager du med dig?':titles[c.topic]}</h1>{c.stage<5?<><p className="learn-task">{prompt(c)}</p>{c.stage===0&&<p className="learn-note">Gæt først. Du behøver ikke være sikker—din idé skal undersøges.</p>}{isTransfer&&<p className="learn-independent">Du arbejder nu selv. Guiden og hjælpelagene er lukket. Feedback kommer først, når du afleverer dit svar.</p>}<div ref={sceneRoot}><Scene context={c} focus={focus} onExplore={n=>update(s=>({...s,context:{...s.context,explore:n},explored:true}))}/></div>
 {c.stage===0&&<fieldset className="learn-options"><legend>Min forudsigelse</legend>{[0,1,2].map((j)=>{const i=(j+c.seed%3)%3,text=choices[c.topic].prediction[i];return <label key={text}><input type="radio" name="prediction" checked={state.prediction===i} onChange={()=>update(s=>({...s,prediction:i}))}/>{text}</label>})}</fieldset>}
 {c.stage===1&&<div className="learn-reflection"><b>Din forudsigelse:</b> {choices[c.topic].prediction[state.prediction]}<p>{!state.explored?'Undersøg figuren og sammenlign med din forudsigelse.':c.topic==='geometry'?`I din figur er hældningen nu ${fmt(d.currentSlope)} mod ${fmt(d.baseSlope)} ved start. Den vandrette afstand er stadig ${d.dx}. Prøv B flyttet 2 op, og sammenlign med din forudsigelse.`:'Når kun den største observation vokser, vokser summen. Den midterste observation bliver på samme plads.'}</p><p>Flyt selv kontrollen mindst én gang, før du går videre. {state.explored?'✓ Du har undersøgt ændringen.':''}</p></div>}
 {(c.stage===2||c.stage===4)&&<div className="learn-answer"><label>{c.topic==='geometry'?'Hældningskoefficient':'Gennemsnit i minutter'}<input aria-label={c.topic==='geometry'?'Hældningskoefficient':'Gennemsnit'} inputMode="decimal" maxLength={100} value={work.first} onChange={e=>write({first:e.target.value})}/></label>{c.topic==='statistics'&&<label>Median i minutter<input aria-label="Median" inputMode="decimal" value={work.second} maxLength={100} onChange={e=>write({second:e.target.value})}/></label>}</div>}
 {c.stage===3&&<fieldset className="learn-options"><legend>Vælg den begrundelse, du vil bygge videre på</legend>{[0,1,2].map((j)=>{const i=(j+c.seed%3)%3,text=choices[c.topic].explanation[i];return <label key={text}><input type="radio" name="reason" checked={work.choice===i} onChange={()=>write({choice:i})}/>{text}</label>})}</fieldset>}
 {(c.stage===3||c.stage===4)&&<label className="learn-writing">Forklar med dine egne ord<textarea value={work.explanation} maxLength={1200} onChange={e=>write({explanation:e.target.value})} placeholder={c.topic==='geometry'?'Hvilke forskelle bruger du, og hvorfor?':'Hvordan vil du beskrive data, og hvad skjuler hvert mål?'}/><small>Din tekst gemmes til refleksion. Den bliver ikke automatisk godkendt som et bevis.</small></label>}
 {c.stage>=2&&<button className="learn-secondary" onClick={()=>void assess()}>{c.stage===4?'Aflever mit forsøg':c.stage===3?'Tjek mit valg':'Tjek min beregning'}</button>}
 {status&&<div role="status" className="learn-feedback">{status}</div>}{c.stage===4&&state.passed[4]&&<div className="learn-reflection"><b>Kontrollér selv din forklaring</b><p>{c.topic==='geometry'?'Har du trukket koordinaterne fra i samme rækkefølge? Forklarer du det negative fortegn med, at linjen falder fra P til Q?':'Har du forklaret, at medianen er robust over for den lange ventetid? Har du også nævnt, at gennemsnittet inddrager alle venteminutter?'}</p></div>}
 <div className="learn-next"><button disabled={c.stage===0} onClick={()=>go((c.stage-1) as Stage)}>← Tilbage</button><button className="learn-primary" disabled={!canNext} onClick={()=>go((c.stage+1) as Stage)}>{c.stage===4?'Se mit tilbageblik':`Videre: ${steps[c.stage+1]}` } →</button></div></>:<><div className="learn-summary"><h2>{c.topic==='geometry'?'Hældning forbinder to ændringer':'To mål fortæller forskellige historier'}</h2><p>{c.topic==='geometry'?'Hældningen er ændringen i y divideret med ændringen i x. Et negativt fortegn beskriver en faldende linje.':'Gennemsnittet bruger alle værdiernes størrelse. Medianen afhænger af deres rækkefølge og er mere robust over for ekstreme observationer.'}</p><dl><dt>Din første forudsigelse</dt><dd>{choices[c.topic].prediction[state.prediction]}</dd><dt>Beregning i den nye opgave</dt><dd>{state.attempts[4]===1?'Korrekt ved første aflevering':'Korrekt efter feedback og nye forsøg'}</dd><dt>Støtte undervejs</dt><dd>{state.assisted?'Du brugte AI under det guidede forløb.':'Ingen AI-hjælp registreret.'} Udforskning og forklaringer var en del af forløbet.</dd></dl><p>Dette viser, hvad der skete i denne runde. Det beviser ikke, at emnet er mestret. Prøv en ny situation igen en anden dag.</p></div><label className="learn-writing">Hvad hjalp dig—og hvad var uklart?<textarea value={state.feedback} maxLength={1000} onChange={e=>setState(s=>s?{...s,feedback:e.target.value}:s)}/></label><button className="learn-primary" onClick={exportFeedback}>Eksportér forløb og feedback</button><button className="learn-secondary" onClick={()=>start(c.topic)}>Prøv en ny runde</button></>}{error&&<p role="alert" className="learn-error">{error} Dit arbejde er bevaret.</p>}</div>
 {c.stage<4&&<aside className="learn-guide"><button className="learn-guide-toggle" aria-expanded={guideOpen} onClick={()=>setGuideOpen(v=>!v)}>Har du brug for et lille skub? {guideOpen?'−':'+'}</button>{guideOpen&&<><p>Guiden hjælper med det trin og den figur, du ser. Prøv først selv.</p><label><input type="checkbox" checked={state.ai} onChange={e=>update(s=>({...s,ai:e.target.checked}))}/> AI-hjælp {state.ai?'til':'fra'}</label><div className="learn-chat" aria-live="polite">{state.messages.map((m,i)=><p key={i}><b>{m.role==='student'?'Dig':'Guide'}:</b> {m.text}</p>)}</div><label>Dit spørgsmål<textarea value={question} maxLength={1000} onChange={e=>setQuestion(e.target.value)} placeholder="Jeg forstår ikke, hvorfor…"/></label><button className="learn-secondary" disabled={!state.ai||!available||busy} onClick={()=>void ask()}>{busy?'Guiden tænker…':'Hjælp mig videre'}</button>{busy&&<button onClick={cancel}>Stop</button>}<small>{available?'Opgave, dit svar og figuren sendes via det lokale Codex-login, når du spørger.':'AI er ikke tilgængelig. De faste forklaringer og alle trin virker stadig.'}</small></>}</aside>}
 </main></div>;
}
